apiVersion: v1
kind: Secret
metadata:
  name: os-service-secrets
type: Opaque
stringData:
  DB_HOST: ""
  DB_PORT: "3306"
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: "os_service_db"
  MONGO_URI: ""
  MONGO_DB_NAME: "os_service_mongo"
  JWT_SECRET: ""
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: ""
  SQS_QUEUE_URL: ""
  SQS_DLQ_URL: ""
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
